name: Update Data

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every 1 minute
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Adding this line will enable manual triggering.
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install beautifulsoup4

      - name: Run Python script
        env:
          GITHUB_PAT: ${{ secrets.PAT }}  # Pass the GitHub PAT as an environment variable
        run: python node.py  # Execute the Python script to update the JSON file

      - name: Commit changes
        run: |
          git config user.name "obi-wan-xenobi"
          git config user.email "obiwanxenobi@gmail.com"
          git add -A
          git commit -m "Update data"
          git push

          if git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
          fi
          timestamp=$(date -u)
          git commit -m "Data updated on ${timestamp}" || exit 0
          git pull --rebase origin main
          git push https://${{ secrets.PAT }}@github.com/obi-wan-xenobi/Node-Ranking.git HEAD:main
      
