name: Update Data

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt && pip install beautifulsoup4

    - name: Run Python script
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  # Pass the GitHub PAT as an environment variable
      run: python Node_output.py  # Execute the Python script to update the JSON file

    - name: Commit changes
      run: |
        git config user.name "obi-wan-xenobi"
        git config user.email "obiwanxenobi@gmail.com"
        git add .
        git commit -m "Update data"
        git push
